import type { NextConfig } from 'next'
import { createMDX } from 'fumadocs-mdx/next'

const config: NextConfig = {
  reactStrictMode: true,
  transpilePackages: ['@stackform/core', '@stackform/ui', '@stackform/rhf'],
  typescript: {
    // .source/index.ts is generated by fumadocs-mdx and has @ts-nocheck,
    // but Next.js still surfaces TS2742 on its exported declaration.
    // Run `pnpm typecheck` separately for source-level type checking.
    ignoreBuildErrors: true,
  },
}

const withMDX = createMDX()

export default withMDX(config)
